name: event_app
description: Event App Dunia Coding
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: any

dependencies:
  another_flushbar: ^1.12.30
  auto_size_text: ^3.0.0
  bloc: ^8.1.1
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^9.0.0
  get: ^4.6.5
  get_it: ^7.2.0
  good_search_appbar: ^0.0.2
  google_fonts: ^4.0.3
  intl: ^0.18.0
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.1.0
  table_calendar: ^3.0.9

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
